server:
  port: 8124
  servlet:
    context-path: /fileapi
spring:
  application:
    name: file_uploader_backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/file_uploader
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
##  激活读取配置(可以直接在运行配置开）
#  profiles:
#    active: local
  # Redis 配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000

#配置下划线转驼峰,这里不需要，关了
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.oranges.fileuploaderbackend.controller